name: Dotnet CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Google Cloud
      run: |
        apt-get update && apt-get install -y curl python3 python3.8-venv python3-dev python3-pip
        curl https://sdk.cloud.google.com | bash
        PATH=$PATH:/root/google-cloud-sdk/bin
  
    - name: Installing Google Cloud and setting credentials
      run: |
          cd dotnet
          echo ${{ secrets.GCP_JSON }} > gcp.json
          export GOOGLE_CREDENTIALS=$(cat gcp.json)
          export GOOGLE_APPLICATION_CREDENTIALS=gcp.json
          echo "GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS"
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"

    - name: Installing Google Cloud and setting credentials
      run: |
          echo $GCP_JSON > gcp.json
          export GOOGLE_CREDENTIALS=$(cat gcp.json | jq -c )
          export GOOGLE_APPLICATION_CREDENTIALS=gcp.json
          echo "GOOGLE_CREDENTIALS: $GOOGLE_CREDENTIALS"
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
      env:
        GCP_JSON: ${{ secrets.GCP_JSON }}
  
    - name: Auth with Google Cloud (in correct directory)
      working-directory: dotnet  # Ensure you are in the right directory
      run: |
          gcloud auth activate-service-account pipeline-onboarding@toolbox-sandbox-388523.iam.gserviceaccount.com --key-file=gcp.json
          gcloud config set project toolbox-sandbox-388523
          gcloud auth configure-docker
