name: Dotnet CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'dotnet/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Installing Google Cloud
      run: |
        apt-get update && apt-get install -y curl python3 python3.8-venv python3-dev python3-pip
        curl https://sdk.cloud.google.com | bash
        PATH=$PATH:/root/google-cloud-sdk/bin

    - name: Installing Google Cloud
      run: |
        cd dotnet
        echo $GCP_JSON > ${{ github.workspace }}/dotnet/gcp.json
        ls ${{ github.workspace }}
        cat gcp.json | jq -c
        export GOOGLE_CREDENTIALS=$(cat ${{ github.workspace }}/dotnet/gcp.json | jq -c )
        export GOOGLE_APPLICATION_CREDENTIALS=gcp.json

    - name: Installing Google Cloud
      run: |
        cat ${{ github.workspace }}/dotnet/gcp.json
        gcloud auth activate-service-account pipeline-onboarding@toolbox-sandbox-388523.iam.gserviceaccount.com --key-file=${{ github.workspace }}/dotnet/gcp.json
        gcloud config set project toolbox-sandbox-388523
        gcloud auth configure-docker
