name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t nodejs-ci-cd .

    - name: Push Docker image to Docker Hub
      env:
        # Adicione aqui no arquivo yaml do GH actions o username e senha do Docker Hub.
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker tag nodejs-ci-cd $DOCKER_HUB_USERNAME/nodejs-ci-cd
        docker push $DOCKER_HUB_USERNAME/nodejs-ci-cd
